In [6]:
import numpy as np
import scipy as sp
import scipy.stats as st
from scipy import linalg as sl

print ("Modules Imported!")

Modules Imported!


In [7]:
#help function here

#give S return [S]
def braS(w):
    return np.array([[0,-w[2],w[1],w[3]],[w[2],0,-w[0],w[4]],[-w[1],w[0],0,w[5]],[0,0,0,0]])

print ("Function Imported!")

Function Imported!


In [8]:
# joint infomation:
w =[[0,0,1],
    [0,1,0],
    [0,1,0],
    [0,1,0],
    [1,0,0],
    [0,1,0]]

q = [[-0.15,0.15,0.01],
     [-0.15,0.27,0.162],
     [0.094,0.27,0.162],
     [0.307,0.177,0.162],
     [0.307,0.26,0.162],
     [0.39,0.26,0.162]]

M= [[0,-1,0,0.39],
    [0,0,-1,0.401],
    [1,0,0,0.2155],
    [0,0,0,1]]

v=[]
ST=[]
for i in range(6):
    v.append(-np.cross(np.array(w[i]),np.array(q[i])))
    ST.append(w[i]+list(v[i]))
S = np.array(ST).T

def HomT(S, theta):
    theta = np.array(theta)/180*np.pi
    T = np.dot(np.dot(np.dot(np.dot(np.dot(np.dot(sl.expm(braS(S[:,0])*theta[0]),sl.expm(braS(S[:,1])*theta[1])),sl.expm(braS(S[:,2])*theta[2])),sl.expm(braS(S[:,3])*theta[3])),sl.expm(braS(S[:,4])*theta[4])),sl.expm(braS(S[:,5])*theta[5])),M)
    print(T)
    return T
def d06(T):
    return T[    :3    ,3]
v

[array([ 0.15,  0.15, -0.  ]),
 array([-0.162,  0.   , -0.15 ]),
 array([-0.162, -0.   ,  0.094]),
 array([-0.162, -0.   ,  0.307]),
 array([-0.   ,  0.162, -0.26 ]),
 array([-0.162, -0.   ,  0.39 ])]

In [11]:
theta = [[-40,-50,75,-30,-90,0],
         [20,-45,105,-60,-90,0],
         [-105,-105,100,-50,-110,-30],
         [-15,-80,90,-50,-45,-20],
         [-15,-40,55,-40,-90,-25],
         [35,-35,25,-20,-90,0],
         [10,-25,35,-45,-90,10]]
print('test')
for i in range(5):
    print('T06 0f test',i+1,"is")
    print('d06 of test',i+1,"is",d06(HomT(S,theta[i])))



test
T06 0f test 1 is
[[ 0.64278761 -0.76312941 -0.06676517  0.2958759 ]
 [ 0.76604444  0.64034161  0.05602263 -0.01070021]
 [ 0.         -0.08715574  0.9961947   0.12566763]
 [ 0.          0.          0.          1.        ]]
d06 of test 1 is [ 0.2958759  -0.01070021  0.12566763]
T06 0f test 2 is
[[-3.42020143e-01 -9.39692621e-01 -7.61837614e-17  1.34280436e-01]
 [ 9.39692621e-01 -3.42020143e-01  5.12902306e-18  4.27462683e-01]
 [ 0.00000000e+00  2.14607521e-16  1.00000000e+00  9.07064360e-03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
d06 of test 2 is [0.13428044 0.42746268 0.00907064]
T06 0f test 3 is
[[ 0.79749685 -0.28901683  0.52959234 -0.12664993]
 [-0.16797404  0.73672124  0.65500117 -0.16975584]
 [-0.57946829 -0.61131913  0.53898554  0.37724118]
 [ 0.          0.          0.          1.        ]]
d06 of test 3 is [-0.12664993 -0.16975584  0.37724118]
T06 0f test 4 is
[[-0.49365465 -0.60775435 -0.6220448   0.24472603]
 [ 0.82017711 -0.08752883 -0.565374

In [10]:
print('question:\n')
print('transform matrix for config1 is:')
T5 = HomT(S,theta[5])
print('d06 for config1 is\n',d06(T5))

print('\ntransform matrix for config2 is:')
T6 = HomT(S,theta[6])
print('d06 for config2 is\n',d06(T6))

question:

transform matrix for config1 is:
[[-0.57357644 -0.70940648 -0.40957602  0.20840632]
 [ 0.81915204 -0.49673176 -0.28678822  0.60055545]
 [ 0.         -0.5         0.8660254   0.25833013]
 [ 0.          0.          0.          1.        ]]
d06 for config1 is
 [0.20840632 0.60055545 0.25833013]

transform matrix for config2 is:
[[-0.03092682 -0.82460528 -0.56486252  0.4002032 ]
 [ 0.99454677  0.03092682 -0.0996005   0.4122126 ]
 [ 0.0996005  -0.56486252  0.81915204  0.16556683]
 [ 0.          0.          0.          1.        ]]
d06 for config2 is
 [0.4002032  0.4122126  0.16556683]


In [46]:
import sympy as syp
n=6;
thetas = syp.symbols(['theta'+str(1+k) for k in range(6)], real=True);
type(thetas[1])
s = [syp.Matrix(braS(S[:,i])*thetas[i]) for i in range(6)]
expT = [syp.simplify(syp.exp(s[i]))for i in range(6)]

In [54]:
expT[0]

Matrix([
[1.0*cos(θ1), -1.0*sin(θ1),   0,  0.15*sqrt(2)*sin(θ1 + pi/4) - 0.15],
[1.0*sin(θ1),  1.0*cos(θ1),   0, -0.15*sqrt(2)*cos(θ1 + pi/4) + 0.15],
[          0,            0, 1.0,                                   0],
[          0,            0,   0,                                 1.0]])

In [47]:
expT[1]

Matrix([
[ 1.0*cos(θ2),   0, 1.0*sin(θ2),  -0.162*sin(θ2) + 0.15*cos(θ2) - 0.15],
[           0, 1.0,           0,                                     0],
[-1.0*sin(θ2),   0, 1.0*cos(θ2), -0.15*sin(θ2) - 0.162*cos(θ2) + 0.162],
[           0,   0,           0,                                   1.0]])

In [48]:
expT[2]

Matrix([
[ 1.0*cos(θ3),   0, 1.0*sin(θ3), -0.162*sin(θ3) - 0.094*cos(θ3) + 0.094],
[           0, 1.0,           0,                                      0],
[-1.0*sin(θ3),   0, 1.0*cos(θ3),  0.094*sin(θ3) - 0.162*cos(θ3) + 0.162],
[           0,   0,           0,                                    1.0]])

In [49]:
expT[3]

Matrix([
[ 1.0*cos(θ4),   0, 1.0*sin(θ4), -0.162*sin(θ4) - 0.307*cos(θ4) + 0.307],
[           0, 1.0,           0,                                      0],
[-1.0*sin(θ4),   0, 1.0*cos(θ4),  0.307*sin(θ4) - 0.162*cos(θ4) + 0.162],
[           0,   0,           0,                                    1.0]])

In [50]:
expT[4]

Matrix([
[1.0,           0,            0,                                     0],
[  0, 1.0*cos(θ5), -1.0*sin(θ5),   0.162*sin(θ5) - 0.26*cos(θ5) + 0.26],
[  0, 1.0*sin(θ5),  1.0*cos(θ5), -0.26*sin(θ5) - 0.162*cos(θ5) + 0.162],
[  0,           0,            0,                                   1.0]])

In [51]:
expT[5]

Matrix([
[ 1.0*cos(θ6),   0, 1.0*sin(θ6), -0.162*sin(θ6) - 0.39*cos(θ6) + 0.39],
[           0, 1.0,           0,                                    0],
[-1.0*sin(θ6),   0, 1.0*cos(θ6), 0.39*sin(θ6) - 0.162*cos(θ6) + 0.162],
[           0,   0,           0,                                  1.0]])